<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="sim_create_base">

    <xacro:property name="diffdrive_update_rate" value="40"/>
    <xacro:property name="wheel_torque" value="0.5"/>
    <xacro:property name="wheel_accel" value="0.5"/>

    <gazebo>
      <!-- Diff-drive controller -->
      <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <alwaysOn>true</alwaysOn>
        <rosDebugLevel>na</rosDebugLevel>
        <updateRate>${diffdrive_update_rate}</updateRate>
        <leftJoint>left_wheel_joint</leftJoint>
        <rightJoint>right_wheel_joint</rightJoint>
        <wheelSeparation>${wheel_separation}</wheelSeparation>
        <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
        <wheelTorque>${wheel_torque}</wheelTorque>
        <wheelAcceleration>${wheel_accel}</wheelAcceleration>
        <commandTopic>cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>
        <robotBaseFrame>base_footprint</robotBaseFrame>
        <publishWheelTF>true</publishWheelTF>
        <publishOdomTF>true</publishOdomTF>
        <publishWheelJointState>true</publishWheelJointState>
        <legacyMode>false</legacyMode>
        <odometrySource>map</odometrySource>
        <publishTf>1</publishTf>
      </plugin>

      <!-- Ground truth -->
      <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>60.0</updateRate>
        <bodyName>base_link</bodyName>
        <topicName>gts</topicName>
        <gaussianNoise>0</gaussianNoise>
        <frameName>/map</frameName>
        <xyzOffsets>0 0 0</xyzOffsets>
        <rpyOffsets>0 0 0</rpyOffsets>
      </plugin>
    </gazebo>

    <gazebo>
      <plugin name="virtual_wall_detector" filename="libvirtual_wall_detector.so"/>
    </gazebo>

    <!-- Bumpers -->
    <gazebo reference="base_link">
      <gravity>true</gravity>
      <self_collide>false</self_collide>
      <maxContacts>10</maxContacts>
      <sensor name='bumper_contact_sensor' type='contact'>
        <always_on>true</always_on>
        <update_rate>50</update_rate>
        <contact>
          <collision>base_link_collision</collision>
        </contact>
        <!-- Plugin -->
        <plugin name="create_bumper_controller" filename="libcreate_bumper_plugin.so">
          <frameName>base_link</frameName>
          <bumperTopicName>bumper</bumperTopicName>
        </plugin>
      </sensor>
    </gazebo>

    <!-- Wheels -->

    <gazebo reference="left_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
      <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="right_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
      <material>Gazebo/Grey</material>
    </gazebo>

  </xacro:macro>

</robot>
